version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY = "your_openai_api_key_here"
      - MODEL = "Your_Model_Name_Here"
    networks:
      - default

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  redis_data:

networks:
  default:
    driver: bridge
 
 
 
 
